export const SET_MOVIES = "SET_MOVIES";
export const SET_COLUMNS = "SET_COLUMNS";
export const SET_INITIAL_MOVIES_IDS = "SET_INITIAL_MOVIES_IDS";
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'
